### ISSUE TITLE
cmake command fails

### ISSUE THREAD

**Issue by padsley** [rlongland/RatesMC#14]
```
CMake Error at CMakeLists.txt:18 (file):
  file COPY cannot find
  "/paths/to/RatesMC/RatesMCGithub/RatesMC.in".

```
This likely means that there needs to be a RatesMC.in file in the home directory in order to build the project.

**Comment by rlongland** [comment]
Should be fixed with 37d0f87563489c29158c7e1bab4a09e5478d2fd1
