### ISSUE TITLE
Compile Error on Ubuntu Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by gchristian321** [rlongland/RatesMC#20]
A recent upgrade to Ubuntu 22.04 LTS (running g++ 11.2.0) caused a compile error, I believe related to stricter checking of #includes for standard library functions.

Adding
`#include <limits>`

to

`src/Resonance.cpp` and `src/Interference.cpp` fixed it for me.

**Comment by rlongland** [comment]
Thanks, Greg!

Fixed with commit 47f0c7675c40e760e3a4ca8f9630ea2c331d37fe
