### ISSUE TITLE
If the Q-value is negative, the GSL lib will breakdown.

### ISSUE THREAD

**Issue by Liulaixuexi** [rlongland/RatesMC#31]
If the Q-value is negative, the GSL lib will breakdown.

**Comment by rlongland** [comment]
Example:
Q = -221 keV
Er = 408 +/- 173 keV

This resonance has a large non-zero chance of being below the Q-value. Even though Er is positive, it's a sub-threshold resonance. The code should account for these cases correctly.

**Comment by rlongland** [comment]
Correction: If Er<Q, this is non-physical. It suggests a resonance below the ground state.

The code correctly calculates endothermic broad resonances now. And produces an error if Er<Q. In the future, I would like to include uncertain Q in RatesMC and have added it as a feature request.
